### ISSUE TITLE
--tool_cutoff arguments leads to error

### ISSUE THREAD

**Issue by valleema** [matq007/fusion-report#25]
Hello!

I have success running:

```
singularity exec nfcore-rnafusion-1.1.0.img fusion_report run sample . ../databases/ \
--fusioncatcher sample/results/tools/Fusioncatcher/final-list_candidate-fusion-genes.txt \
--starfusion sample/results/tools/StarFusion/star-fusion.fusion_predictions.tsv \
--ericscript sample/results/tools/Ericscript/tmp/fusions.results.filtered.tsv \
--pizzly sample/results/tools/Pizzly/pizzly_fusions.txt \
--squid sample/results/tools/Squid/fusions_annotated.txt
```

but if add (short or long argument name):

```
singularity exec nfcore-rnafusion-1.1.0.img fusion_report run sample . ../databases/ \
--fusioncatcher sample/results/tools/Fusioncatcher/final-list_candidate-fusion-genes.txt \
--starfusion sample/results/tools/StarFusion/star-fusion.fusion_predictions.tsv \
--ericscript sample/results/tools/Ericscript/tmp/fusions.results.filtered.tsv \
--pizzly sample/results/tools/Pizzly/pizzly_fusions.txt \
--squid sample/results/tools/Squid/fusions_annotated.txt \
-t 1
```

It outputs this error:

```
Running application...
Traceback (most recent call last):
  File "/opt/conda/envs/nf-core-rnafusion-1.1.0/bin/fusion_report", line 12, in <module>
    app.run()
  File "/opt/conda/envs/nf-core-rnafusion-1.1.0/lib/python3.7/site-packages/fusion_report/app.py", line 58, in run
    self.generate_report(params)
  File "/opt/conda/envs/nf-core-rnafusion-1.1.0/lib/python3.7/site-packages/fusion_report/app.py", line 88, in generate_report
    'index_summary', self.manager, params={'tool_cutoff': params.tool_cutoff}
  File "/opt/conda/envs/nf-core-rnafusion-1.1.0/lib/python3.7/site-packages/fusion_report/common/base_page.py", line 30, in add_module
    self.modules[name] = ModuleLoader(manager, params).exec(name)
  File "/opt/conda/envs/nf-core-rnafusion-1.1.0/lib/python3.7/site-packages/fusion_report/modules/loader.py", line 24, in exec
    variables = self.__build_factory(name, self.manager, self.params).load()
  File "/opt/conda/envs/nf-core-rnafusion-1.1.0/lib/python3.7/site-packages/fusion_report/modules/index_summary/index_summary.py", line 105, in load
    'fusion_list': self.create_fusions_table(),
  File "/opt/conda/envs/nf-core-rnafusion-1.1.0/lib/python3.7/site-packages/fusion_report/modules/index_summary/index_summary.py", line 63, in create_fusions_table
    filter_flag = len(tools) < self.params['tool_cutoff']
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by matq007** [comment]
Hi @valleema, thank you for reporting the issue. I will deal with it.
