### ISSUE TITLE
HTTP Error 404 with `fusion_report download`

### ISSUE THREAD

**Issue by yuifu** [matq007/fusion-report#44]
Hi! I came across HTTP Error 404 with `fusion_report download`. This error occurred when I used fusion-report alone or called fusion-report via nf-core/rnafusion. 

Is there any way to avoid this error?

Here is how to reproduce:

```
wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
bash Miniforge3-Linux-x86_64.sh

conda activate
conda create -y -n rnafusion python=3.8.2
conda activate rnafusion
conda install -c bioconda fusion-report=2.1.4

fusion_report download --cosmic_usr ID --cosmic_passwd PASSWORD outdir
```

Here is the message:

```
Downloading resources...
Downloading db.tar.gz
HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/site-packages/fusion_report/common/net.py", line 50, in get_large_file
    with urllib.request.urlopen(url, context=ctx) as response:
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/site-packages/fusion_report/app.py", line 70, in run
    Download(params)
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/site-packages/fusion_report/download.py", line 25, in __init__
    self.download_all(params)
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/site-packages/fusion_report/download.py", line 46, in download_all
    Net.get_cosmic(self.cosmic_token, return_err)
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/site-packages/fusion_report/common/net.py", line 81, in get_cosmic
    Net.get_large_file(auth_url)
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/site-packages/fusion_report/common/net.py", line 59, in get_large_file
    raise DownloadException(ex)
fusion_report.common.exceptions.download.DownloadException: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/bin/fusion_report", line 13, in <module>
    app.run()
  File "/lustre7/home/lustre3/harukao/miniforge3/envs/rnafusion/lib/python3.8/site-packages/fusion_report/app.py", line 77, in run
    raise AppException(ex)
fusion_report.common.exceptions.app.AppException: HTTP Error 404: Not Found
HTTP Error 404: Not Found
```

**Comment by matq007** [comment]
Hi @yuifu, yes I am aware of the issues. The problem is that Mitelman database has been moved to different location. I am slowly working on a new version of fusion-report.

**Comment by yuifu** [comment]
@matq007 Thanks for the quick reply! Now I understand the situation.
I am looking forward to using the new version in the near future:-)
